Maska989/testStrchr
phoenix-rtos/phoenix-rtos-tests pull request #169
Opened 2023-02-28 12:23 UTC by maska989

## Description

Added Strchr and Strrchr test cases
## Motivation and Context

JIRA: CI-211

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [x] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-04-12 06:50 UTC, maska989 commented on libc/string_chr.c
> +	char str[PATH_MAX] = "a";
``` c
for (int i = 0; i < PATH_MAX - 5; i++) {

		if (i == PATH_MAX - 10) {
			strcat(str, "b");
		}
		else
			strcat(str, "a");
	}
```
That's why it is not const.

2023-04-12 08:04 UTC, niewim19 commented on libc/string_chr.c
> +	}
```suggestion
	memset(str, 'a', PATH_MAX - 5);
	str[PATH_MAX - 10] = 'b';
```

Much shorter. Though it needs `str` declaration as follows:
```c
char str[PATH_MAX] = { 0 };
```

Also:
 - `-5` and `-10` seems rather arbitrary. 
 - this test may be split into two: one with _loremipsum_ usage and other with `PATH_MAX` case. But that`s just a suggestion.
 - it is unclear why we use one type of string for forward search (`strchr`) but very different string for reverse search (strrchr).

2023-04-12 08:06 UTC, damianloew commented on libc/string_chr.c
> +	char str[PATH_MAX] = "a";
Yeah, that's right, but there were other cases.

2023-04-12 08:08 UTC, niewim19 commented on libc/string_chr.c
> +	}
Or if you`re very eager on not using `memset` you can just:
```suggestion
	for (i = 0; i < PATH_MAX - 5; i++) {
		str[i] = 'a';
	}
	str[PATH_MAX - 10] = 'b';
```

2023-04-17 13:45 UTC, damianloew requested changes
A few changes required to simplify this tests and provide the better coverage.

2023-04-17 13:45 UTC, damianloew commented on libc/string_lenchr.c
> +	str[i - 1] = '\0';
Not needed as str is initialized to zeros.

2023-04-17 13:45 UTC, damianloew commented on libc/string_lenchr.c
> +	TEST_ASSERT_EQUAL_STRING(NULL, memchr(whites, 'x', strlen(whites)));
We decided to split test cases to smaller ones in `chr` tests, so please create a separate test case `whitespacees` and place the mentioned code there. Above that I know that I suggested you the solution with `xwhites`, but now I see that checking \0 as the last character would be sufficient, so please take the `" \v\t\r\n"` string and est chr functions for space, termination char, some char in the middle, for example \t and x which is not present in the mentioned string.

```suggestion
```

2023-04-17 13:45 UTC, damianloew commented on libc/string_lenchr.c
> +	TEST_ASSERT_EQUAL_STRING(notAsciiSet, memchr(notAsciiSet, notAsciiSet[0], sz));
We can also check notAsciiSet[128] and notAsciiSet[64].

2023-04-17 13:45 UTC, damianloew commented on libc/string_lenchr.c
> +	TEST_ASSERT_EQUAL_STRING("", strchr(empty, '\0'));
In my opinion it's not needed to declare empty variable, we can just pass "" everywhere.

```suggestion
	TEST_ASSERT_EQUAL_STRING("", strchr("", '\0'));
```

2023-04-17 13:45 UTC, damianloew commented on libc/string_lenchr.c
> +	/* Testing capability of size in memchr with different sizes of reads */
```suggestion
	/* Testing capability of setting size in memchr */
```

2023-04-17 13:45 UTC, damianloew commented on libc/string_lenchr.c
> +TEST(string_chr, ascii_cases)
```suggestion
TEST(string_chr, ascii)
```

2023-04-17 13:45 UTC, damianloew commented on libc/string_lenchr.c
> +	TEST_ASSERT_EQUAL_STRING("baaa", memchr(str, 'b', sizeof(str)));
You can add there checks similar to the ones from the previous test cases, so above that you can add checking:

- the termination character
- the first character
- the character, which is not present in the string

2023-04-20 18:20 UTC, damianloew requested changes
Thanks for changes, as you can see it looks much cleaner now :) Just a few suggestions left

2023-04-20 18:20 UTC, damianloew commented on libc/string_lenchr.c
> +			   *strMod = "Lorem %d/%f/%x/%i/%c/%s Ipsum";
(strWhites) You have now the separate test case for white spaces, so it's not needed there. Above that special characters do not include white spaces, so it's not the place for it, we want to test only special characters there.

(strMod) Modifiers are nothing more than a combination of a % (one of the special characters, which are tested in this test case) and a letter (tested in the `basic` test case). That's why there is no need to test `strMod`. Modifiers are specific for functions like `scanf` or `printf` and then the behavior for different modifiers should be tested.

```suggestion
```

2023-04-20 18:20 UTC, damianloew commented on libc/string_lenchr.c
> +	const char whites[] = " \v\t\r\n";
What about `\f` and other white spaces?

2023-04-20 18:20 UTC, damianloew commented on libc/string_lenchr.c
> +	TEST_ASSERT_EQUAL_STRING(NULL, memchr("", '\v', sz));
Not necessarily needed, we have the edge cases like first character (and last in the same time - \0) and the character which does not exist in the string (space)

```suggestion
```

2023-04-20 18:20 UTC, damianloew commented on libc/string_lenchr.c
> +
\0 and 0 are the same character

```suggestion
	TEST_ASSERT_EQUAL_STRING("", strchr("", '\0'));
	TEST_ASSERT_EQUAL_STRING("", strrchr("", '\0'));
	TEST_ASSERT_EQUAL_STRING("", memchr("", '\0', sz));
```

2023-04-20 18:20 UTC, damianloew commented on libc/string_lenchr.c
> +	RUN_TEST_CASE(string_chr, whitespaces);
Please move the whitespaces case between `special` and `ascii`. Now we have tested whitespaces in the `ascii` case, so it's not so valuable. We want to test some basic stuff, special characters and whites in the separate cases before the whole ascii set to eventually catch smaller issues (for example if handling white spaces didn't work we want to see error of `whitespaces` test case, not `ascii`, which would also fail)

2023-04-25 15:52 UTC, damianloew reviewed
Seems to be fine :+1: Please squash the changes to one commit accroding to our convention, so it would be `libc: string.h: add chr functions tests` (and of course the appropriate JIRA tag below)

2023-04-26 08:49 UTC, damianloew approved these changes

2023-04-26 08:49 UTC, merged