trunner: host can modify runner context
phoenix-rtos/phoenix-rtos-tests pull request #189
Opened 2023-04-04 12:37 UTC by jsarzy

## Description

Add `add_to_context` method in the Host class to allow to change the runner context by host instance. It can be useful in runner extensions. For example, host can read environment variables and add them to context kwargs that later can be used in tests.

Add new keyword to yaml config named kwargs. Kwargs should be a dict, similar to python **kwargs parameter. It can be useful to define custom values in yaml config that later can be read in tests. Kwargs for test are merged with kwargs passed using `--kwargs` flag. If there is the same key in both kwargs dicts then runner choose one from the context.

Definiton of the harness that uses `**kwargs`:
```
def harness(dut, **kwargs): ....
def harness(dut, ctx, **kwargs): ...
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-04-13 11:03 UTC, damianloew requested changes

2023-04-14 10:14 UTC, jsarzy commented on trunner/harness/pyharness.py
> +            # If there is **kwargs in definition then pass dut and kwargs, else pass dut and context
This comment is under the if statement with a condition for 2 arguments, so there can be only dut and kwargs, or dut and context.

2023-04-14 10:14 UTC, jsarzy commented on trunner/harness/pyharness.py
> +            raise HarnessError("harness can be defined only with one, two or three parameters! (dut and ctx)")
Thanks, fixed

2023-04-14 10:15 UTC, jsarzy commented
Applied changes and improved comments.

2023-04-14 13:38 UTC, damianloew approved these changes

2023-04-14 13:57 UTC, merged