libc: scanf: re-enable issued cspn_ptr test
phoenix-rtos/phoenix-rtos-tests pull request #265
Opened 2023-10-02 11:17 UTC by maska989

## Description
JIRA: CI-356 

## Motivation and Context
Enabled test because of fix :  Scanf doesn't read 0x0 as null pointer #677 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [x] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: ia32-generic-qemu, armv7a9-zynq7000-zedboard.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-10-02 13:26 UTC, mateusz-bloch approved these changes
Overall, it looks good, but I have a few nitpicks:
- Wouldn't it be better if `libc: scanf: move scanf outside stdlib` commit was the first one?
-  I would change commit message for `libc: scanf: move scanf outside stdlib` to: 
```
libc: move scanf tests outside stdio
Moved to a separate binary because the `armv7m4-stm32l4x6-nucleo`  has a limited amount of RAM
```
-  I would change commit message for `libc: scanf: re-enable issued cspn_ptr test` to: 
```
scanf: re-enable cspn_ptr test case
Enabled test case because of fix:  Scanf doesn't read 0x0 as null pointer #677 
```

2023-10-02 14:12 UTC, badochov approved these changes
LGTM

2023-10-02 16:56 UTC, damianloew requested changes
Looks good, small remark about a commit description.

Maybe: 

`The updated stdio binary with scanf tests exceeded available ram space on stm32l4x6-nucleo.`

or at least:

`Moved because of armv7m4-stm32l4x6-nucleo ram size problem.`

2023-10-03 09:49 UTC, damianloew approved these changes
LGTM

2023-10-03 09:50 UTC, merged