libc: Add missing asserts for malloc
phoenix-rtos/phoenix-rtos-tests pull request #293
Opened 2023-11-14 10:21 UTC by maska989

JIRA: CI-386

## Description
Fixes: phoenix-rtos/phoenix-rtos-project#920

## Motivation and Context

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [x] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: host-generic-pc / ia32-generic-qemu.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-11-14 11:28 UTC, damianloew requested changes
When your commit fixes some issue please always leave such line in the commit description:

Fixes: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/issue_nr

2023-11-14 11:28 UTC, damianloew commented on libc/string/string_tokpbrkstr.c
> +	TEST_ASSERT_NOT_NULL(testStr);
It also has to be done in line ~770.

2023-11-14 11:28 UTC, damianloew commented on libc/string/string_tokpbrkstr.c
> +	TEST_ASSERT_NOT_NULL(testStr);
And in `string_lenchr.c`

2023-11-14 11:28 UTC, damianloew commented on libc/string/string_tokpbrkstr.c
> +	TEST_ASSERT_NOT_NULL(asciiStr);
Thanks for adding also those missing checks, Could you please also do it next to all `testdata_createCharStr` calls?

2023-11-14 11:28 UTC, damianloew commented on libc/stdio/stdio_file.c
> -
Thanks for those fixes, however it should be done in the separate commit as it's not related to malloc asserts, maybe: `libc: remove unnecessary whitespaces`

2023-11-14 16:15 UTC, damianloew approved these changes
Thanks for fixes :)

2023-11-14 16:16 UTC, damianloew requested changes
EDIT: missing:
![Screenshot from 2023-11-14 17-15-44](https://github.com/phoenix-rtos/phoenix-rtos-tests/assets/77304431/e38cb33b-8bc4-4276-9a8d-b7698d88b2c7)

2023-11-14 16:25 UTC, nalajcie commented
> EDIT: missing: ![Screenshot from 2023-11-14 17-15-44](https://user-images.githubusercontent.com/77304431/282846931-e38cb33b-8bc4-4276-9a8d-b7698d88b2c7.png)

better to use short notation (`Fixes: phoenix-rtos/phoenix-rtos-project#920`), hopefully better with external tools/ possible organization name changes, etc. 

This syntax is also required by GH docs: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2023-11-15 17:24 UTC, mateusz-bloch commented on libc/string/string_cmp.c
> +
checking hugeStr before memcpy

2023-11-16 13:40 UTC, damianloew approved these changes
LGTM

2023-11-16 13:40 UTC, merged