armv7a9: fix problem with magic number
phoenix-rtos/phoenix-rtos-tests pull request #296
Opened 2023-11-14 15:33 UTC by maska989

JIRA: CI-387

## Description

## Motivation and Context

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [X] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [X] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing linter checks and tests passed.
- [X] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-11-14 15:42 UTC, damianloew requested changes

2023-11-14 15:42 UTC, damianloew commented on trunner/target/armv7a9.py
> +            self.dut.expect_exact("Waiting for input", timeout=0.5)
In fact you are expecting "Waiting for input" 2 times (it's already done in enter_bootloader)

```suggestion
```

2023-11-14 15:42 UTC, damianloew commented on trunner/target/armv7a9.py
> +            if "\x1b[31m" in self.dut.before:
Why you are expecting red color? There may be some other error - we want to catch it. I'd let the magic error happen and leave a comment why.

2023-11-21 14:10 UTC, mateusz-bloch commented on trunner/harness/plo.py
> +        # If armv7a9-zynq7000-zedboard is flashed first time (or after full flash0 erase) it will throw error magic
```suggestion
        # If armv7a9-zynq7000-zedboard is flashed for the first time (or after full flash0 erase) it will throw error magic
```

2023-11-21 14:10 UTC, mateusz-bloch commented on trunner/harness/plo.py
> +        # number mismatch, to avoid interrupt and flash it anyway those are taken as false negative and execute further
maybe it would be better to write:
magic number mismatch error, instead error magic number mismatch

2023-11-24 15:15 UTC, damianloew reviewed
Please apply @mateusz-bloch suggestions and we can merge it :)

2023-11-27 13:38 UTC, mateusz-bloch approved these changes

2023-12-13 16:55 UTC, damianloew commented
Closed, because it's not necessary anymore: https://github.com/phoenix-rtos/phoenix-rtos-project/pull/943

2023-12-13 16:55 UTC, closed without merging