libc: disable unix socket tests on zynq qemu
phoenix-rtos/phoenix-rtos-tests pull request #331
Opened 2024-03-04 12:14 UTC by adamdebek

JIRA: CI-404

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [x] I will merge this PR by myself when appropriate.

2024-03-04 13:10 UTC, mateusz-bloch commented on libc/test.yaml
> +        exclude: [armv7m4-stm32l4x6-nucleo, armv7a9-zynq7000-qemu]
I see, the issue with the tests taking too long relates to the test cases:` unix_msg_data_and_fd` and `unix_msg_fork`. Could we split each of these into two separate test cases, for example one for `SOCK_STREAM` and one for `SOCK_DGRAM`? This way, we could run them on every target, given that the issue here is simply that the Nucleo and Zynq-QEMU targets are slow.

2024-03-13 15:48 UTC, mateusz-bloch reviewed
Also change the commit message

2024-03-13 15:48 UTC, mateusz-bloch commented on libc/socket/unix-socket.c
> +TEST(test_unix_socket, unix_stream_sock_send_data)
Not that test case? From what I see, these should be changed:  `unix_msg_data_and_fd` & `unix_msg_fork` :

Zynq-qemu
![image](https://github.com/phoenix-rtos/phoenix-rtos-tests/assets/116297248/a3864b1c-1e8c-4feb-9bfc-21be4e58b2cd)

stm32:
![image](https://github.com/phoenix-rtos/phoenix-rtos-tests/assets/116297248/e6baa681-078e-4fdb-89a2-95697a77de66)

2024-03-13 15:49 UTC, mateusz-bloch commented on libc/test.yaml
> -        exclude: [armv7m4-stm32l4x6-nucleo]
delete `# Excluded due to long execution time`

2024-03-20 11:19 UTC, damianloew requested changes
Thanks for the PR, have you made sure that fails are no longer seen?

2024-03-20 11:19 UTC, damianloew commented on libc/socket/unix-socket.c
> +TEST(test_unix_socket, unix_stream_sock_send_and_fd)
I think that we can remove this `unix` prefix as it's mentioned in the name of test group. Then we can name it `msg_data_and_fd_strem`. The current name is misleading - send and file descriptor, send what (?), also it's not only sending, but receiving too. IMHO it's better to keep the previous convention, where we have test cases like `data_only` and `data_and_fd`

2024-03-20 11:19 UTC, damianloew commented on libc/socket/unix-socket.c
> +TEST(test_unix_socket, unix_stream_sock_send_and_fd)
We can name the same way the rest of changed cases.

2024-03-20 11:56 UTC, mateusz-bloch commented
> Thanks for the PR, have you made sure that fails are no longer seen?

Yes,  from what I remember, in the worst-case scenario there's about a +-12-second safety margin.

2024-03-20 12:15 UTC, damianloew approved these changes
LGTM, Could you please update submodules after a merge?

2024-03-20 14:45 UTC, merged