pshlogin: tests of login utility
phoenix-rtos/phoenix-rtos-tests pull request #36
Opened 2021-07-16 12:34 UTC by niewim19

Tests added for:
 - pshlogin (only ia32)
 - auth applet (all arch)

JIRA: PD-75

## Description
Two separate tests added as it is now impossible to properly test `pshlogin` on imxrt1064 (it needs binary rename).
 - `test-pshlogin.py` tests launching psh with login prompt. It does not test exitability as it needs launching it as a first psh. It is currently only for ia32
- `test-auth.py` is a similar test to `test-pshlogin.py` but it launches login prompt using `auth` command accessible in `psh`. It is a way to test login logic (searching for password etc) works without spawning new `psh`

## Motivation and Context

Those two tests, with current state of repository, checks if everything works correctly with login related components of Phoenix-RTOS

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2021-07-21 09:04 UTC, jsarzy requested changes
Overall it looks good, some remarks regarding to coding style.

Please split tools:
1. `tools.py` -> `tools/basic.py`
2. `tools_login.py` -> `tools/login.py`

It will require some changes in the other psh tests.
Also keep import in some order:
1. All standard library imports
2. External library imports
3. Our files

All these separated by a new line. It's suggestion but I think it will help us to keep imports readable

2021-07-21 13:25 UTC, niewim19 commented on psh/test-auth.py
> +def logging_in(p, login, passwd, iscorrect):
Wrapper removed. Thanks

2021-07-21 13:35 UTC, niewim19 commented on psh/test-auth.py
> +    p.send('\x04')
Added `EOT` global

2021-07-21 13:37 UTC, niewim19 commented on psh/test-auth.py
> +    p.send(tools.cred_bad.login + '\n')
Credentials moved to tests

2021-07-21 13:37 UTC, niewim19 commented on psh/test-auth.py
> +        p.send('\x08')
Added `BACKSPACE` global. Thanks

2021-07-21 13:38 UTC, niewim19 commented on psh/tools_login.py
> +psh_run_cmd = '/bin/pshlogin'
Good idea. Changed as requested.

2021-07-21 13:38 UTC, niewim19 commented on psh/tools_login.py
> +Credentials = namedtuple('Credentials', 'login passwd')
Yea, this is good. Changed `login` to `user`. Thanks

2021-07-21 13:45 UTC, niewim19 commented on psh/tools_login.py
> +def login_procedure(p, login, passwd, iscorrect):
Function split is implemented. I just left three separate functions:
 - `assert_login`
 - 'assert_login_failed`
 - 'assert_login_empty'

two of them are somehow similar but i left them as it is not to introduce too much complexity (`assert_login` and `assert_login_failed` differ by only one line)

2021-07-21 13:46 UTC, niewim19 commented on psh/tools_login.py
> +        if iscorrect is True:
iscorrect was removed all together

2021-07-21 13:46 UTC, niewim19 commented on psh/tools_login.py
> +import pexpect
implemented correct spaces between imports

2021-07-21 13:47 UTC, niewim19 commented on psh/tools_login.py
> +def get_all_ascii():
Thanks for that suggestion! Implemented

2021-07-21 13:49 UTC, niewim19 commented
@jsarzy Thanks for review. Beside code changes I also implemented a change in `psh` tests directory structure. `tools` directory was created and tool files `basics` and `login` reside there. Necessary changes were made to other `psh` tests.

2021-07-22 07:18 UTC, jsarzy requested changes

2021-07-22 07:18 UTC, jsarzy commented on psh/test-pshlogin.py
> +    err = p.expect_exact(['Login:', '(psh)%', pexpect.TIMEOUT], timeout=1)
Please use `idx` instead of `err`, is not some kind of error code

2021-07-22 07:18 UTC, jsarzy commented on psh/test-pshlogin.py
> +#     logintools.login_procedure(p, login, passwd, iscorrect)
Remove commented code

2021-07-22 07:18 UTC, jsarzy commented on psh/test-pshlogin.py
> +    printables = string.printable
This variable is not needed, just use `string.printable`

2021-07-22 07:18 UTC, jsarzy commented on psh/test-auth.py
> +    printables = string.printable
this variable is not needed, just use string.printable

2021-07-22 09:09 UTC, niewim19 commented
Summary comment to last code review.

Thank you for all notes! All were implemented as stated.

2021-07-22 10:19 UTC, niewim19 commented
Changes in good direction. Tests are now clearer. LGTM

2021-07-22 10:20 UTC, jsarzy approved these changes
LGTM

2021-07-22 10:57 UTC, merged