trunner: add Sparcv8Leon3_Generic target support
phoenix-rtos/phoenix-rtos-tests pull request #372
Opened 2024-09-18 08:12 UTC by maska989

JIRA: CI-474

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (refactoring, style fixes, git/CI config, submodule management, no code logic changes)

## How Has This Been Tested?

- [X] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [X] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing linter checks and tests passed.
- [X] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [X] This PR needs additional PRs to work
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1167
- [ ] I will merge this PR by myself when appropriate.

2024-09-18 08:24 UTC, damianloew requested changes
Please enable this target to CI in a separate commit.

2024-09-18 08:24 UTC, damianloew commented on mem/test.yaml
> +        exclude: [armv7m7-imxrt106x-evk, armv7m7-imxrt117x-evk, armv7m4-stm32l4x6-nucleo,sparcv8leon3-generic-qemu]
We want to add a target as experimental for now as we only run psh tests, please see
https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/366#discussion_r1721838618

2024-09-18 10:28 UTC, mateusz-bloch commented on trunner/target/emulated.py
> +
```suggestion
    rootfs = False
    experimental = True
```

And then include `sparcv8leon3-generic-qemu` to psh tests

2024-09-18 10:40 UTC, mateusz-bloch reviewed
When building with tests option

```
LD  test_mmap               
/src/phoenix-rtos-tests/devices/grlib-multi/test-grlib-multi.c:28:2: error: #error "Unsupported target"
   28 | #error "Unsupported target"
      |  ^~~~~
/src/phoenix-rtos-tests/devices/grlib-multi/test-grlib-multi.c:31:10: fatal error: grlib-multi.h: No such file or directory
   31 | #include <grlib-multi.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [../phoenix-rtos-build/Makefile.common:211: /src/_build/sparcv8leon3-generic-qemu/phoenix-rtos-tests/devices/grlib-multi/test-grlib-multi.o] Error 1
make: *** Waiting for unfinished jobs....
```

2024-09-18 10:58 UTC, mateusz-bloch commented
> When building with tests option
> 
> ```
> LD  test_mmap               
> /src/phoenix-rtos-tests/devices/grlib-multi/test-grlib-multi.c:28:2: error: #error "Unsupported target"
>    28 | #error "Unsupported target"
>       |  ^~~~~
> /src/phoenix-rtos-tests/devices/grlib-multi/test-grlib-multi.c:31:10: fatal error: grlib-multi.h: No such file or directory
>    31 | #include <grlib-multi.h>
>       |          ^~~~~~~~~~~~~~~
> compilation terminated.
> make: *** [../phoenix-rtos-build/Makefile.common:211: /src/_build/sparcv8leon3-generic-qemu/phoenix-rtos-tests/devices/grlib-multi/test-grlib-multi.o] Error 1
> make: *** Waiting for unfinished jobs....
> ```

You could add this to the Makefile.sparcvleon3, or come up with better solution

```
ifneq ($(TARGET), sparcv8leon3-generic-qemu)
DEFAULT_COMPONENTS += test-grlib-multi
endif
```

2024-09-18 12:19 UTC, mateusz-bloch commented on psh/test.yaml
>            targets:
On the beginning of yaml should be smth like:
```yaml
test:
    targets:
      #TODO: remove when sparcv8leon3-generic-qemu target will stop being experimental
      include: [sparcv8leon3-generic-qemu]
```

2024-09-23 14:25 UTC, mateusz-bloch commented on trunner/target/emulated.py
> +        )
Nit: For future: changes about  formatting of untouched parts of  file should not be part of the same pr

2024-09-27 09:09 UTC, mateusz-bloch commented on psh/test.yaml
> +        value: [sparcv8leon3-generic-qemu]
You should include target, not set sparcv8leon3-generic-qemu as only target, also comment should be place why it is done.
```suggestion
        include: [sparcv8leon3-generic-qemu]
```

2024-10-03 15:05 UTC, mateusz-bloch commented on Makefile.sparcv8leon3
> +ifneq ($(TARGET), sparcv8leon3-generic-qemu)
Could also do this in a separate commit and be connected to this issue: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1182

2024-10-03 15:33 UTC, damianloew commented on Makefile.sparcv8leon3
> +ifneq ($(TARGET), sparcv8leon3-generic-qemu)
Yeah, it should be done in the separate commit for sure

2024-10-11 11:03 UTC, damianloew requested changes

2024-10-11 11:03 UTC, damianloew commented on Makefile.sparcv8leon3
> +ifneq ($(TARGET), sparcv8leon3-generic-qemu)
@maska989 please create a separate commit for excluding this test from build

2024-10-11 11:25 UTC, damianloew reviewed
Some notes about commit descriptions.

As it's described in our `Golden Rules`

 - describe WHY You're doing the change in the commit message body

So you don't want to repeat what you have added in the commit message body (called also commit description). In your case the reason of adding a new target is rather obvious - we just want to support all of our available targets.

About the second commit `sparcv8leon3: prevent from building test-grlib-multi on qemu target` - the commit title shows perfectly what is going on in this change, you probably want to add information WHY do we need to exclude it, so a good commit description would be:

```
This test is not intended to build on this particular target.
```

2024-10-11 11:52 UTC, damianloew approved these changes

2024-10-11 11:53 UTC, merged