resolve_path: missing_dir should return NULL
phoenix-rtos/phoenix-rtos-tests pull request #40
Opened 2021-07-27 11:06 UTC by niewim19

JIRA: PD-160

## Description

According to (https://github.com/phoenix-rtos/libphoenix/pull/117) resolve_path should return NULL if presented a path with missing branch (not missing leaf). This PR changes output expected by test.

## Motivation and Context

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [x] This PR needs additional PRs to work (https://github.com/phoenix-rtos/libphoenix/pull/117)
- [ ] I will merge this PR by myself when appropriate.

2021-08-09 16:55 UTC, nalajcie requested changes
Please add more currently-failing paths to prevent regressions in the future (as proposed in https://github.com/phoenix-rtos/libphoenix/pull/117#issuecomment-895379881)

2021-08-09 16:55 UTC, nalajcie commented on libc/resolve_path.c
> +	check_and_free_str(NULL, resolve_path("/etc/missing_dir/.", NULL, 1, 1));
please change it to `check_null_and_errno`

2021-08-10 12:56 UTC, niewim19 commented
Looks like old artefacts were supplied, as fix is merged and test fails like there was no fix

Tests locally:
![image](https://user-images.githubusercontent.com/80880689/128870562-df334b55-0097-4bc9-ada8-cc4bb2cf626f.png)

2021-08-10 13:12 UTC, niewim19 commented
Tests fail due to runner taking repo without fix (without updated submodules)

2021-08-10 13:20 UTC, nalajcie commented
> Tests fail due to runner taking repo without fix (without updated submodules)

This is how it should work - it takes current `phoenix-rtos-project` and updates only the submodule with PR. I'll merge this in a sec and update the submodules in phoenix-rtos-project via PR - then we will be sure the tests are passing in CI.

2021-08-10 13:20 UTC, nalajcie approved these changes

2021-08-10 13:21 UTC, merged